# Generated by Django 6.1 on 2026-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodewarsKata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kata_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('rank_name', models.CharField(blank=True, max_length=100)),
                ('rank_slug', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('total_completed', models.PositiveIntegerField(default=0)),
                ('total_attempted', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
