# Generated by Django 6.1 on 2026-08-27 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('submitted', 'Submitted'), ('grading', 'Grading'), ('graded', 'Graded'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='invitations.invitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('code_answer', models.TextField(blank=True)),
                ('score_earned', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.question')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='answers', to='assessments.choice')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='attempts.attempt')),
            ],
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['assessment', 'candidate'], name='attempts_at_assessm_e64c99_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status'], name='attempts_at_status_3196f6_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['candidate', 'status'], name='attempts_at_candida_ef8156_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('assessment', 'candidate'), name='one_active_attempt_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='one_answer_per_question_attempt'),
        ),
    ]
