# Generated by Django 6.1 on 2026-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bdd_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='pseudocode_answer',
            field=models.TextField(blank=True),
        ),
    ]
